apiVersion: v1
kind: Pod
metadata:
  name: devops-app
  labels:
    app: devops-tool
    environment: staging
    team: platform
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sh", "-c", "echo DevOps multi-label pod running && sleep 3600"]
